language: java
branches:
    only:
    - master
jdk:
- oraclejdk8
script:
- gradle build
- gradle bintrayUpload
before_install:
- sudo add-apt-repository -y ppa:cwchien/gradle
- sudo apt-get install -y gradle
- openssl aes-256-cbc -K $encrypted_72c58051a96a_key -iv $encrypted_72c58051a96a_iv
  -in gradle.properties.enc -out gradle.properties -d
- gradle -v
