language: java
branches:
    only:
    - master
jdk:
- oraclejdk8
script:
- ./gradlew build
- ./gradlew bintrayUpload
before_install:
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_72c58051a96a_key -iv $encrypted_72c58051a96a_iv
  -in gradle.properties.enc -out gradle.properties -d
- ./gradlew -v
